version: "2"

services:
  traefik:
    links:
      - rundeck:rundeck.lan
  rundeck:
    # see https://github.com/EugenMayer/rundeck/blob/master/docker-compose.yml
    image: eugenmayer/rundeck:2.11.0
    depends_on:
      - rundeckdb
    # see .env_rundeck
    environment:
      # see .env for explainations and docs
      DB_TYPE: postgresql
      DB_HOST: rundeckdb
      DB_PORT: 5432
      DB_NAME: rundeckdb
      DB_USER: rundeck
      DB_PASSWORD: rundeck
      RUNDECK_WITH_SSL: 0
      EXTERNAL_SERVER_URL: http://rundeck.lan
      RUNDECK_ADMIN_PASSWORD: admin
      RUNDECK_STORAGE_PROVIDER: file
      RUNDECK_PROJECT_STORAGE_TYPE: file
      LOGIN_MODULE: RDpropertyfilelogin
      JAAS_CONF_FILE:
      RD_USER: admin
      RD_PASSWORD: admin
      RD_URL: http://localhost:4440
      SERVER_URL: http://localhost:4440
      RD_BYPASS_URL: http://rundeck.lan
    volumes:
      - rundeck_plugins:/opt/rundeck-plugins
      - rundeck_config:/etc/rundeck
      - rundeck_logs:/var/log/rundeck
      - rundeck_storage:/var/lib/rundeck/var/storage
      - rundeck_tmp:/var/rundeck
    ports:
      - 4440:4440
    extra_hosts:
      - rundeck.lan:127.0.0.1
  rundeckdb:
    image: postgres:9.6
    volumes:
      - rundeck_db:/var/lib/postgresql
    environment:
      POSTGRES_USER: rundeck
      POSTGRES_PASSWORD: rundeck
      POSTGRES_DB: rundeckdb

volumes:
  rundeck_config:
    driver: local
  rundeck_tmp:
    driver: local
  rundeck_storage:
    driver: local
  rundeck_logs:
    driver: local
  rundeck_plugins:
    driver: local
  rundeck_plugins:
    driver: local
  rundeck_db:
    driver: local