version: "2"

services:
  consul:
    image: consul
    command: agent
    environment:
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - ./consul/server.json:/consul/config/server_config.json
      - consul-server-data:/consul/data:rw
    ports:
      - "8500:8500"

volumes:
  consul-server-data:
    driver: local