#file based configuration
version: "2"

services:
  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/endpoints/:/etc/traefik/endpoints
  drupal1:
    image: 'emilevauge/whoami'
  drupal2:
    image: 'emilevauge/whoami'
