#file based configuration
version: "2"

services:
  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/endpoints/:/etc/traefik/endpoints
volumes:
  consul-server-data:
    driver: local
  drupal1:
    image: nginx
  drupal2:
    image: nginx
