#defaultEntryPoints = ["http", "https"]
defaultEntryPoints = ["http"]


# important if we use self-signed certificates on the backends
InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
    
[traefikLog]
  filePath = "/var/log/traefik.log"
  format   = "common"

[accessLog]
  filePath = "/var/log/traefik.access.log"
  format = "common"
  
[file]
  # https://docs.traefik.io/configuration/backends/file/#multiple-separated-files
  directory = "/etc/traefik/endpoints/"
  watch = true

[api]

[ping]

# Enable ACME (Let's Encrypt): automatic SSL.
[acme]
# https://docs.traefik.io/configuration/acme/

#[consul]
#  # Consul server endpoint.
#  endpoint = "consul:8500"
#  # Enable watch Consul changes.
#  watch = true
#  # Prefix used for KV store.
#  prefix = "traefik"
