# https://docs.traefik.io/configuration/backends/file/#reference
[backends]
  [backends.drupal]
    [backends.drupal.servers.server1]
      url = "http://drupal1:80"
    [backends.drupal.servers.server2]
      url = "http://drupal2:80"
    [backends.drupal.healthCheck]
      path = "/"
      port = 80
      interval = "30s"
[frontends]
  [frontends.drupal]
    backend = "drupal"
    # that sets our X-Forward-Host headers
    passHostHeader=true    
    [frontends.drupal.routes.test_1]
      rule = "Host:drupal.lan"
